### PR TITLE
Update Requirements for Source Code.txt

### PR DESCRIPTION
**Pull request by anon-cypher**
[Requirements for Source Code.txt](https://github.com/Harshp20/Instagram_Bot/files/4591277/Requirements.for.Source.Code.txt)

### CODE REVIEW

**Comment by Harshp20** [comment]
> [Requirements for Source Code.txt](https://github.com/Harshp20/Instagram_Bot/files/4591277/Requirements.for.Source.Code.txt)

Hi there! Thanks for contributing. Could you please update the same requirements under the heading “Prerequisites for Executable” in README.md also? Thanks!

**Comment by anon-cypher** [comment]
For sure, i'll update readme.md also in few moments

**Comment by anon-cypher** [comment]
KIndly update chromedrivers for linux and mac in dist folder. As for me it
is disabled , so I can't upload your on repository.

**Comment by Harshp20** [comment]
Thanks! I'll include the chrome drivers for Mac and Linux too.

**Pull request merged**
